version: "3.7"

services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DOCKER_MODE: development
      PORT: 5000
      DATABASE_NAME: maindb
      DATABASE_USERNAME: maindbuser
      DATABASE_PASSWORD: maindbpassword
    ports:
      - 5000:5000
    volumes:
      - "./backend:/app"
      - backend_node_modules:/app/node_modules
    networks:
      - local
    depends_on:
      - mongodb

  mongodb:
    build:
      context: ./mongodb
      dockerfile: Dockerfile
    container_name: mongodb
    environment:
      DATABASE_NAME: maindb
      SUPERUSER_USERNAME: superuser
      SUPERUSER_PASSWORD: superuserpassword
      EXPRESS_USERNAME: expressuser
      EXPRESS_PASSWORD: expresspassword
      DATABASE_USERNAME: maindbuser
      DATABASE_PASSWORD: maindbpassword
      REPLICA_SET_HOST: mongodb
      REPLICA_SET_NAME: my-mongo-set
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_vol:/data/db
      - mongodb_config_vol:/data/configdb
    networks:
      - local
    command: mongod --config /etc/mongo/mongod.conf --configExpand "exec"

  mongo-express:
    image: mongo-express:0.54.0
    container_name: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=expressuser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=expresspassword
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    ports:
      - 8081:8081
    networks:
      - local
    depends_on:
      - mongodb

networks:
  local:

volumes:
  mongodb_data_vol:
  mongodb_config_vol:
  backend_node_modules:
