version: "3.7"

services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DOCKER_MODE: development #Para definir como se debe ejecutar NodeJs: development, production
      PORT: 5000
      DATABASE_NAME: maindb
      DATABASE_REPLICA_SET: my-mongo-set
      DATABASE_USERNAME: maindbuser
      DATABASE_PASSWORD: maindbpassword
    ports:
      - 5000:5000
    volumes:
      - "./backend:/app"
      - backend_node_modules:/app/node_modules
    networks:
      - local
    restart: on-failure
    depends_on:
      - mongodb

  mongodb:
    build:
      context: ./mongodb
      dockerfile: Dockerfile
    container_name: mongodb
    environment:
      DATABASE_NAME: maindb
      SUPERUSER_USERNAME: superuser
      SUPERUSER_PASSWORD: superuserpassword
      DATABASE_USERNAME: maindbuser
      DATABASE_PASSWORD: maindbpassword
      REPLICA_SET_HOST: mongodb
      REPLICA_SET_NAME: my-mongo-set
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_vol:/data/db
      - mongodb_config_vol:/data/configdb
    networks:
      - local
    command: mongod --config /etc/mongo/mongod.conf --configExpand "exec"

networks:
  local:

volumes:
  mongodb_data_vol:
  mongodb_config_vol:
  backend_node_modules:
